package main

import (
	"fmt"
	"io"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"time"
)

// baresipInstance is a baresip child process we own. It writes its config
// and accounts into a tmpdir and shuts down cleanly on Close.
type baresipInstance struct {
	cmd     *exec.Cmd
	tmpDir  string
	logPath string
	addr    string
}

func (b *baresipInstance) Close() {
	if b == nil {
		return
	}
	if b.cmd != nil && b.cmd.Process != nil {
		_ = b.cmd.Process.Kill()
		_, _ = b.cmd.Process.Wait()
	}
	if b.tmpDir != "" {
		_ = os.RemoveAll(b.tmpDir)
	}
}

// spawnBaresip writes a self-contained config + accounts into a tmpdir,
// starts baresip headless against it, waits until ctrl_tcp accepts
// connections, and returns the loopback address it's listening on.
func spawnBaresip(accountsSource string) (*baresipInstance, error) {
	modPath, err := detectModulePath()
	if err != nil {
		return nil, err
	}

	port, err := freeTCPPort()
	if err != nil {
		return nil, fmt.Errorf("find free tcp port: %w", err)
	}

	tmp, err := os.MkdirTemp("", "baresip-mcp-")
	if err != nil {
		return nil, err
	}
	cfgDir := filepath.Join(tmp, ".baresip")
	if err := os.MkdirAll(cfgDir, 0o755); err != nil {
		_ = os.RemoveAll(tmp)
		return nil, err
	}

	// Pick a platform-native audio backend so the user actually hears the
	// remote side. ausine remains the source — we don't grab the mic
	// because multiple parallel baresips would all fight for it.
	audioModule, audioPlayer := platformAudio(modPath)

	cfg := fmt.Sprintf(`# Generated by baresip-mcp — do not edit.
sip_listen              0.0.0.0:0
module_path             %s
module                  g711.so
module                  ausine.so
module                  auconv.so
module                  auresamp.so
module                  account.so
module                  fakevideo.so
module                  menu.so
module                  ctrl_tcp.so
%s
ctrl_tcp_listen         127.0.0.1:%d
audio_source            ausine,440
%s
audio_buffer            20-160
audio_buffer_mode       fixed
`, modPath, audioModule, port, audioPlayer)
	if err := os.WriteFile(filepath.Join(cfgDir, "config"), []byte(cfg), 0o644); err != nil {
		_ = os.RemoveAll(tmp)
		return nil, err
	}

	// Copy accounts file if it exists; otherwise leave empty. The user's
	// real accounts file is the source of truth — we don't synthesize.
	if err := copyAccounts(accountsSource, filepath.Join(cfgDir, "accounts")); err != nil {
		_ = os.RemoveAll(tmp)
		return nil, err
	}

	logPath := filepath.Join(tmp, "baresip.log")
	logFile, err := os.Create(logPath)
	if err != nil {
		_ = os.RemoveAll(tmp)
		return nil, err
	}

	cmd := exec.Command("baresip", "-f", cfgDir)
	cmd.Env = append(os.Environ(), "HOME="+tmp)
	cmd.Stdout = logFile
	cmd.Stderr = logFile
	if err := cmd.Start(); err != nil {
		logFile.Close()
		_ = os.RemoveAll(tmp)
		return nil, fmt.Errorf("start baresip (is it on PATH?): %w", err)
	}

	addr := fmt.Sprintf("127.0.0.1:%d", port)
	if err := waitForCtrlTCP(addr, 5*time.Second); err != nil {
		// Surface baresip's log so the user has a chance at diagnosing.
		_ = cmd.Process.Kill()
		_, _ = cmd.Process.Wait()
		logFile.Close()
		logBody, _ := os.ReadFile(logPath)
		_ = os.RemoveAll(tmp)
		return nil, fmt.Errorf("baresip ctrl_tcp on %s never came up: %w\n--- baresip log ---\n%s", addr, err, logBody)
	}

	return &baresipInstance{
		cmd:     cmd,
		tmpDir:  tmp,
		logPath: logPath,
		addr:    addr,
	}, nil
}

func freeTCPPort() (int, error) {
	l, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		return 0, err
	}
	defer l.Close()
	return l.Addr().(*net.TCPAddr).Port, nil
}

func waitForCtrlTCP(addr string, d time.Duration) error {
	deadline := time.Now().Add(d)
	for time.Now().Before(deadline) {
		conn, err := net.DialTimeout("tcp", addr, 200*time.Millisecond)
		if err == nil {
			_ = conn.Close()
			return nil
		}
		time.Sleep(100 * time.Millisecond)
	}
	return fmt.Errorf("timeout after %s", d)
}

// platformAudio returns the baresip module line and audio_player config
// appropriate for the current OS. Falls back silently if the expected
// module isn't present — the call still works, the user just won't hear
// the remote.
func platformAudio(modPath string) (moduleLine, audioPlayer string) {
	type cand struct{ module, player string }
	var candidates []cand
	switch runtime.GOOS {
	case "darwin":
		candidates = []cand{
			{"coreaudio.so", "audio_player coreaudio,default"},
			{"audiounit.so", "audio_player audiounit,default"},
		}
	case "linux":
		candidates = []cand{
			{"alsa.so", "audio_player alsa,default"},
			{"pulse.so", "audio_player pulse,"},
		}
	}
	for _, c := range candidates {
		if _, err := os.Stat(filepath.Join(modPath, c.module)); err == nil {
			return "module " + c.module, c.player
		}
	}
	return "", ""
}

func detectModulePath() (string, error) {
	candidates := []string{
		"/opt/homebrew/lib/baresip/modules",
		"/usr/local/lib/baresip/modules",
		"/usr/lib/x86_64-linux-gnu/baresip/modules",
		"/usr/lib/aarch64-linux-gnu/baresip/modules",
		"/usr/lib/baresip/modules",
	}
	if p := os.Getenv("BARESIP_MODPATH"); p != "" {
		candidates = append([]string{p}, candidates...)
	}
	for _, c := range candidates {
		if _, err := os.Stat(filepath.Join(c, "ctrl_tcp.so")); err == nil {
			return c, nil
		}
	}
	return "", fmt.Errorf("baresip ctrl_tcp.so module not found in any known path; set BARESIP_MODPATH")
}

func copyAccounts(src, dst string) error {
	if src == "" {
		return os.WriteFile(dst, nil, 0o644)
	}
	in, err := os.Open(src)
	if err != nil {
		if os.IsNotExist(err) {
			// No accounts file at the source — write an empty one and move on.
			return os.WriteFile(dst, nil, 0o644)
		}
		return err
	}
	defer in.Close()
	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()
	_, err = io.Copy(out, in)
	return err
}
